### ISSUE TITLE
Doesn't work in desktop Firefox because `TouchList` is not defined

### ISSUE THREAD

**Issue by ryanatkn** [vaheqelyan/svelte-grid#1]
Firefox supports `TouchList` but on desktop v68 it doesn't define the object on the window, so the code errors here and prevents it from working: https://github.com/vaheqelyan/svelte-grid/blob/1fe43135b64fdf27ef84cbca0a432fc45abfabd9/src/utils/other.js#L12

Very cool project!

**Comment by vaheqelyan** [comment]
It seems to work fine on firefox. Feel free to reopen:)

**Comment by ryanatkn** [comment]
That commit fixes it, thanks!
