### ISSUE TITLE
Canvas size in component to follow parent cell

### ISSUE THREAD

**Issue by j2l** [vaheqelyan/svelte-grid#100]
Following your great solution using components in cells, I tried with canvas, but it doesn't follow the cell size:
Here's `Text.svelte`:
```
<div>
	<canvas id="myCanvas"></canvas>
</div>

<style>
	canvas{
		border:1px solid #000000;
	}
</style>
```
By default, I have something not 100% and I would like it to be 100% of the cell.
![image](https://user-images.githubusercontent.com/65325/127021253-041d9c46-5ef6-4eeb-82b0-dc105368969c.png)

and when I resize the cell, it's not adapting to it:
![image](https://user-images.githubusercontent.com/65325/127020457-14ad9132-0355-40b4-8345-02c80bbf909e.png)

I tried forcing the canvas and the div sizes to 100% without luck.

I'm sure it will be a piece of cake for you to spot the problem :smile: 
Any idea?

**Comment by vaheqelyan** [comment]
i think you should specify `width: 100%` and `height: 100%`

```html
<style>
  #canvas {
    width: 100%;
    height: 100%;
  }
</style>
```

**Comment by j2l** [comment]
I tried it and adding it on both canvas and div did the trick.
Thank you very much @vaheqelyan!
