### ISSUE TITLE
Using Chart JS inside the grid layout, 

### ISSUE THREAD

**Issue by SekSion** [vaheqelyan/svelte-grid#109]
Hey, i was trying to use this to render chart-js dynamicly and everything is great except that im having an issue that on load the draggable container doesnt fit on the chart, here is the photo.

Is there something im missing here?

![image](https://user-images.githubusercontent.com/46030872/142227458-ffb63e73-f103-451a-b740-505d395473cb.png)

**Comment by vaheqelyan** [comment]
Can you share your code using http://svelte.dev/repl please ? It will help me to understand the issue

**Comment by SekSion** [comment]
Sure @vaheqelyan, here it is https://svelte.dev/repl/0b647a52641c4fdf9855f4dcfe7f3a06?version=3.44.2

**Comment by SekSion** [comment]
it seems like the calculations of the wrapper for the draggable element are done before the renderization of the charts, or at least it doenst "refresh" the size of it but its just a guess, can't seem to make a solution to this yet

**Comment by vaheqelyan** [comment]
have a look at this https://svelte.dev/repl/59119f8d9f934f70b6e2a2d04b599aba?version=3.44.2
Removed ```<div class=demo-widget>``` on line 109, or you can set the height to `100%` for the `div` element

**Comment by SekSion** [comment]
then i guess it was my brain that wasnt working correctly to not have seen this cause im sure i tried to set the div to 100% and didint work <.< sorry for your time then mate, thx
