### ISSUE TITLE
[HELP] Changing Data Dinamicly

### ISSUE THREAD

**Issue by SekSion** [vaheqelyan/svelte-grid#112]
Hello, this isnt an actual issue but it is something i need and im not finding it.

Im rendering chartJS inside a grid, but now i need to change the component that is being rendered inside one of the grids, is there a method or a way to refresh just one element of the grid? same thing for a simple text if i wanna change something inside the grid it is not working for me.

**Comment by vaheqelyan** [comment]
Hey SekSion
Take a look at this example https://svelte.dev/repl/24af394e0dda4eae82c10c9a14788352?version=3.44.2
You can use writable stores for your component data

Another solution would be to emit an event from a component you want to update.

**Comment by SekSion** [comment]
i think this helps for my needs, thanks!
