### ISSUE TITLE
Is it does not support other Bundler besides Rollup?

### ISSUE THREAD

**Issue by hmmhmmhm** [vaheqelyan/svelte-grid#13]
![14141](https://user-images.githubusercontent.com/38493722/67135899-29932b80-f25a-11e9-89bb-2700eb4201b2.png)

when i bundle the basic this modules example with rollup, it works.
but it looks like a does not work on parcel or webpack .
(i have set the relevant Svelte bundling modules for each bundler.)

Error Example:
```
Uncaught (in promise) TypeError: Cannot read property 'getBoundingClientRect' of undefined
```
```
Uncaught TypeError: Cannot read property 'x' of undefined
```

**Comment by hmmhmmhm** [comment]
I've found a way to solve this problem.

If you import the code like a below, only rollup that can be recognizes package.json's svelte file, other bundlers doesn't parse package.json svelte file.

```js
import Grid from "svelte-grid"
```

So simply select exactly the svelte file as shown below. Problem solved!

```js
import Grid from "svelte-grid/src/index.svelte"
```

**Comment by vaheqelyan** [comment]
Thanks. I'll try

**Comment by vaheqelyan** [comment]
I think it works. i tried with webpack.
