### ISSUE TITLE
Mobile Safari - Unexpected token '...'. Expected a property name

### ISSUE THREAD

**Issue by lokhmakov** [vaheqelyan/svelte-grid#16]
For proper work should be transpiled without spread operators.

**Comment by vaheqelyan** [comment]
i will use object.assign(). i do not why svelte does not transpile, or i am doing something wrong in my configuration

**Comment by vaheqelyan** [comment]
Checked on browserstack. works fine `svelte-grid`-  `1.11.2` and `svelte` - `^3.24.0`. feel free to reopen
