### ISSUE TITLE
Grid from Components

### ISSUE THREAD

**Issue by Valexr** [vaheqelyan/svelte-grid#18]
How to make Grid from different Components.svelte

**Comment by vaheqelyan** [comment]
Can you describe in more detail please

**Comment by Valexr** [comment]
I'm ReDesigning a website Builder on Svelte and I want to do it on the basis of your grid. You can add components to the page and immediately configure the grid with the component inside the grid slot.
Something like this... https://ru.svelte.dev/repl/398346d75f4144df92b206c6ef19b6f8?version=3.16.0
Old usable example - https://ip.in-sign.ru/admin - admin / 89255289918

**Comment by vaheqelyan** [comment]
https://svelte-grid.now.sh/examples/add_remove Add/Remove example ? 
https://layout-master.now.sh/ ?

**Comment by vaheqelyan** [comment]
You can use global storage to configure grid elements.
```svelte

      let items = [
        {...gridHelp.item({ x: 0, y: 0, w: 2, h: 2, id: id() }), ...{data: {} } },
        {...gridHelp.item({ x: 2, y: 0, w: 2, h: 2, id: id() }), ...{data: {} } }
      ];
```

**Comment by Valexr** [comment]
Okey! Will see. Thnx👍🏻
