### ISSUE TITLE
Unable to use svelte-grid within web componemnt

### ISSUE THREAD

**Issue by ferret13** [vaheqelyan/svelte-grid#20]
When imported inside a svelte web component template I get the following error when compiling;

(!) Plugin svelte: No custom element 'tag' option was specified. To automatically register a custom element, specify a name with a hyphen in it, e.g. <svelte:options tag="my-thing"/>. To hide this warning, use <svelte:options tag={null}/> node_modules/svelte-grid/src/index.svelte
1: <style>
^ 2:   :global(body) {
   3:     overflow: scroll;

Do I need to do something to use nested components?

**Comment by vaheqelyan** [comment]
> When imported inside a svelte web component template I get the following error when compiling;

can you give a link to the repository?

**Comment by vaheqelyan** [comment]
need a repo
