### ISSUE TITLE
Is auto height impossible?

### ISSUE THREAD

**Issue by hmmhmmhm** [vaheqelyan/svelte-grid#21]
Articles are often very irregular in size depending on the
number of characters and are difficult to predict...

Couldn't i dynamically display a grid of texts that are difficult to predict in size?

**Comment by vaheqelyan** [comment]
No, it's impossible, and maybe it's possible. But then it won't be a grid. widgets will cover each other.You better implement the masonry layout.

**Comment by hmmhmmhm** [comment]
Thank you for your reply, I'll let you know when I find the answer later
