### ISSUE TITLE
Webpage crashes

### ISSUE THREAD

**Issue by brdhunga** [vaheqelyan/svelte-grid#24]
When I try to use the code from basic example as a svelte component the web page crashes. 

I tried using sapper and the same thing happened. 

It does not give any error either in npm terminal or in the browser.

**Comment by vaheqelyan** [comment]
I'm pretty sure this is related to the compiler and not how the component is written.what version do you use?

**Comment by vaheqelyan** [comment]
OK, I checked the latest version of the compiler and it crashed, I agree.

**Comment by vaheqelyan** [comment]
this is probably related to https://github.com/sveltejs/svelte/issues/4325.

**Comment by vaheqelyan** [comment]
Try to do so.
`var items = [..]`
to
`var items_arr = [..]`
and
`<Grid {items} bind:items .. >`
to
`<Grid items={items_arr} bind:items={items_arr} .. >`

**Comment by brdhunga** [comment]
I tried making your suggestions and it still does not work. 

I am using the following compiler and library versions:

>     "svelte": "^3.0.0",
>     "svelte-grid": "latest"

I renamed the  items array to items_arr like you suggested:
`  let items_arr = [gridHelp.item({ x: 0, y: 0, w: 2, h: 2, id: id() }), gridHelp.item({ x: 2, y: 0, w: 2, h: 2, id: id() })];`

The html part looks like this:
```
<Grid items={items_arr} bind:items={items_arr} cols={4} let:item rowHeight={100}>
  <div class="content" style="background: #ccc; border: 1px solid black;">
    {item.id}
  </div>
</Grid>
```

**Comment by brdhunga** [comment]
However, turns out the repl using svelte 3.7.1. When using svelte 3.7.1, I can confirm that it works,

**Comment by vaheqelyan** [comment]
The latest version (in this case, 3.20.1) works.
Feel free to reopen!
