### ISSUE TITLE
prevent onmousedown on grid.items' content to drag item 

### ISSUE THREAD

**Issue by frantic0** [vaheqelyan/svelte-grid#25]
Hi @vaheqelyan,

I want to prevent the onmousedown on the grid.items' content to drag item. In my use case, I have an editor which is contained by the grid item and can not select the text has it drags the item.

Or can I restrict event a specific area of the grid.items' content? 

Many thanks,
F0

**Comment by vaheqelyan** [comment]
if your editor covers the entire widget. and you want to disable onmousedown,in your case you want to select text without dragging.
you can wrap the editor or any other element in a div. add the onmousedown event, and call event.stopPropagation.but after that you can't drag the widget anymore.

**Comment by vaheqelyan** [comment]
Solutions for
> but after that you can't drag the widget anymore.

Imagine that your widget has a height of 100px. make the editor have a height of 80px.wrap in div. disable the mouse down event for this part.the remaining space can be left for drag.

**Comment by vaheqelyan** [comment]
I write from a mobile. I hope I helped you.

**Comment by frantic0** [comment]
It helped! thank you very much

**Comment by frantic0** [comment]
Hi @vaheqelyan 

I noticed a regression on my project at the level of grid items content. 

When I try to select text content from a grid item, now the item is moved 

I used 

`on:mousedown={ e => e.stopPropagation() } `

as below, to prevent the event from propagating down the component hierarchy. I stopped working, any suggestion on how to sort this? 



```
<Grid items={$items}
        {breakpoints}
        {cols}
        {rowHeight}
        {gap}
        useTransform
        let:item
        on:adjust={onAdjust}
        on:mount={onChildMount}
        >

    <span class='move' >+</span>
          <!-- style="background: { item.static ? '#bka' : item.background }; border: { item.hasFocus ? '5px solid red': '5px solid blue' } ;" -->

    <div  class="content"
          style="background: { item.static ? '#bka' : item.background }; border: { item.hasFocus ? '1px solid rgba(100, 100, 100, 0.5)': '1px solid rgba(25, 25, 25, 1)' }; border-width: 1px 0px 0px 1px;"
          on:mousedown={ e => e.stopPropagation() } >

      <span class='close'
            on:click={ () => remove(item) } >✕</span>

  		<svelte:component class='component' 
                        this={item.component}
                        {...item}
                        on:change={ e => update(item, e.detail.prop, e.detail.value) } />

    </div>
```


Many thanks,
FØ

**Comment by vaheqelyan** [comment]
try `on:pointerdown ' instead of `on:mousedown`. I agree that this is annoying, very annoying, for both user and developer.

**Comment by vaheqelyan** [comment]
I hope that this example will be another solution to this issue https://svelte-grid.now.sh/examples/custom-dragger

**Comment by frantic0** [comment]
thanks @vaheqelyan

replacing *on:mousedown* by *on:pointerdown* fixed text selection inside the grid-item.
