### ISSUE TITLE
Not working in Svelte 3.17.0+

### ISSUE THREAD

**Issue by cpsTinK** [vaheqelyan/svelte-grid#26]
See https://svelte.dev/repl/35a506b9456d463ab441841859e1bb9f?version=3.17.0

**Comment by MintyMods** [comment]
Tricky to even debug that as it seems to go into a loop and the page becomes non responding

**Comment by MintyMods** [comment]
Can also be reproduced against `3.16.5` but not against `3.16.0`  which is very similar to the following open [Svelte issue](https://github.com/sveltejs/svelte/issues/4129).

**Comment by vaheqelyan** [comment]
guys I will try to update the component this week.but most of the issues come from svelte itself

**Comment by vaheqelyan** [comment]
Yes indeed 3.17.0 crashes. But version 3.20.1 works as it should.
Feel free to reopen
