### ISSUE TITLE
How serialize and restore ?

### ISSUE THREAD

**Issue by cpsTinK** [vaheqelyan/svelte-grid#27]
> - Layout can be serialized and restored

There is no single example of how to do this...

**Comment by MintyMods** [comment]
You have to find it :) 

See the following [example](https://github.com/vaheqelyan/svelte-grid/blob/9eed4096aef5eb9132575d1ae547fe9204d6c957/www/src/routes/examples/localStorage.svelte#L68) based on issue #7 - that should point you in the right direction

**Comment by vaheqelyan** [comment]
this week I will try to update the dependencies. and update the site

**Comment by vaheqelyan** [comment]
[https://svelte-grid.now.sh/examples/localStorage](https://svelte-grid.now.sh/examples/localStorage)
It does not appear in route /examples
