### ISSUE TITLE
Store for Grid Items with subcomponent hierarchies 

### ISSUE THREAD

**Issue by frantic0** [vaheqelyan/svelte-grid#28]
Hi @vaheqelyan, 

I was wondering if you could provide some insights about using stores for state management of the svelte-grid items list (or layout).

I'm considering a specific use case in which grid items encapsulate different types of subcomponent hierarchies. For instance, some grid-items encapsulate text-editor components, others have charts components.

The grid items are created dynamically and in a number determined by the user, and their subcomponents require state persistence in a store, and will be updated with a fast rate.

It's difficult to find good examples in Svelte of more complex store architecture with the hierarchical state... It is a bit strange to do it with single-level, flat stores.  What would be the best approach given how the svelte-grid works?

Thanks in advance,
Francisco

**Comment by vaheqelyan** [comment]
I'll think about it

**Comment by theWebalyst** [comment]
Tagging this because I may want to do something similar: persistence of layouts and some degree of hierarchy.

**Comment by vaheqelyan** [comment]
Maybe it's something similar to what you're looking for, [https://layout-master.now.sh/](https://layout-master.now.sh/) ?

This is the only thing I wrote on svelte and svelte-grid

[https://github.com/vaheqelyan/layout-master](https://github.com/vaheqelyan/layout-master)

[index.js](https://github.com/vaheqelyan/layout-master/blob/master/src/routes/index.svelte)
[store.js](https://github.com/vaheqelyan/layout-master/blob/master/src/store/index.js)

**Comment by vaheqelyan** [comment]
I did this little demo [repl](https://svelte.dev/repl/bfd8ee412e9c463b999fe6a66ba6861b?version=3.7.1)
Check it out, too

**Comment by frantic0** [comment]
thanks @vaheqelyan! I'll have a look

**Comment by frantic0** [comment]
Hi @vaheqelyan, 

thanks, your demo repl made me understand better how to use 'svelte:component' for the subcomponent hierarchies.  

However, I still think it doesn't show to use of subcomponent hierarchies with hierarchical state stores. Especially with dynamic components such as the grid-items of svelte-grid...

I forked your repl and tried to evolved it to try to show the problem better... Have a look at this [fork](https://svelte.dev/repl/462673737b004b379c6479eb9c99feee?version=3.7.1):

I created a new component from the <svelte:self> example that builds a component tree from a JSON with a hierarchical a filesystem-like tree. 

One thing to notice is if you collapse a folder and increment a counter, the tree is re-rendered. 

Some questions:
How would you implement the update method for the items store in such a way that would support the renaming of each "folder" in the tree?
How would you structure the store differently to prevent the re-rendering of the whole svelte-grid?
How would you structure the store differently, if you didn't care about the total re-rendering?

Thanks!

**Comment by frantic0** [comment]
Just noticed something else... 

In the [repl](https://svelte.dev/repl/462673737b004b379c6479eb9c99feee?version=3.7.1), the Random component is getting updated but not triggering a total re-rendering? How come?

**Comment by vaheqelyan** [comment]
[repl](https://svelte.dev/repl/7997f19ff7de4da48379c146a5182ccc?version=3.7.1). Simple recursion is used. every time you rename a folder name, you update all the items. The update occurs when the input is blurred. I know the interface isn't the best. (It is for quick work.)

**Comment by frantic0** [comment]
Hi @vaheqelyan, 

thanks for this, and apologies for letting all this time go by without following up...

I understand your solution, you extracted a new store to recursively update the tree state of the Folder component. It works well for reading and writing with one fixed Folder component.

However, how would you go at implementing a store the Folder components dynamically?
