### ISSUE TITLE
Possible style issues

### ISSUE THREAD

**Issue by nibarulabs** [vaheqelyan/svelte-grid#30]
Hello! Thanks for the cool component.

I have two 'issues' with it. 

First is:

```
:global(body) {
    overflow: scroll;
}
```

That causes some scrollbar visual issues in my container element. It draws a little white rectangle at the bottom right (sorry, I didn't take a screenshot). The only way to fix this is to disable and remove svelte-grid. Trying to override in my component or at my scss page level doesn't work. My app background is a darker color and the little white rectangle showing up is not something I can have.

Second is how to pin the svelte-grid component to my element that contains the grid? I was able to do this after my component (that contains svelte-grid) mounted and I did the document hight calcs manually. But when I move a grid item and the drop it, the grid container resizes. 
My use for this is not to have a scrolling grid so much as it is to allow moving around of items in a fixed height scenario.

Thanks again.

**Comment by vaheqelyan** [comment]
I apologize for the late response.
The scrollable object must be at least a container. You can try to remove global overflow and apply overflow: scroll to your container. (when I say container, I mean <Grid/> wrapped in a div. Do not apply to "svlt-grid-container"). For the second case https://github.com/vaheqelyan/svelte-grid/issues/6. 
I will look more closely when I get some free time.

**Comment by nibarulabs** [comment]
Ok, I will give that a try. Thanks.

**Comment by BogdanDarius** [comment]
@vaheqelyan Can you remove `:global(body)` by default? It would be much better to add own global styles if needed, because right now I'm overriding `:global(body)` and I dont actually need a global style for body. Thanks!

**Comment by vaheqelyan** [comment]
`:global(body)` removed in v2, feel free to reopen
