### ISSUE TITLE
gap don't working

### ISSUE THREAD

**Issue by rushelex** [vaheqelyan/svelte-grid#31]
Hello! Thanks for this repo!

I wanted to put spaces between the tiles, but when I set the “gap” property, the tile flies off the screen when moving.

**Comment by vaheqelyan** [comment]
Can you reproduce ? ([repl](https://svelte.dev/repl/hello-world?version=3.22.3))

**Comment by vaheqelyan** [comment]
Can you reproduce ? ([repl](https://svelte.dev/repl/hello-world?version=3.22.3))
