### ISSUE TITLE
useTransform slows down

### ISSUE THREAD

**Issue by rushelex** [vaheqelyan/svelte-grid#32]
When I use the "useTransform" property and the style for the "transition: transform 0.2s" tile, it moves with a long delay when moving it.

If you do the same for .svlt-shadow-shadow, then the shadow moves pretty well, but not like in the example on the main page of the site https://svelte-grid.now.sh/.

**Comment by vaheqelyan** [comment]
Can you reproduce ? ([repl](https://svelte.dev/repl/hello-world?version=3.22.3))

**Comment by rushelex** [comment]
I cannot reproduce this in the REPL, since for example, you need to supplement the source code. If you provide the REPL with the source code, I will try to reproduce the problem.

**Comment by vaheqelyan** [comment]
it probably shouldn't happen in v2, feel free to reopen
