### ISSUE TITLE
Feature : free position option

### ISSUE THREAD

**Issue by trufa2017** [vaheqelyan/svelte-grid#33]
Could there be a way to prevent it from moving the existing widgets and aligning them top -left ?  

this happens mostly since the click event as far as i could see in the code, really advanced thinking by the way, couldn't grasp allot of what's done there

thank you so much, i love this component !!!

**Comment by vaheqelyan** [comment]
If I understand you correctly, You need to set the value `false` for the property `fillEmpty`

`fillEmpty` - Fills empty spaces with a widget if the widget fits in an empty space

But I think it's broken. at the moment

**Comment by trufa2017** [comment]
Thanks for the quick response, you are right , there is fillEmpty, got it . I will be watching this awesome component :) 

Thanks again !
