### ISSUE TITLE
Reactive movement?

### ISSUE THREAD

**Issue by slightlyfaulty** [vaheqelyan/svelte-grid#34]
Is it possible to reposition other elements reactively while dragging or resizing an element?

Example: https://strml.github.io/react-grid-layout/examples/0-showcase.html

I looked through the docs and examples, but couldn't find anything relating to this.

**Comment by vaheqelyan** [comment]
yes it is absolutely possible
https://github.com/vaheqelyan/svelte-grid/blob/master/src/index.svelte#L251
try to change the value for the `dragDebounceMs` property.. I haven't even thought about it since writing this component. try and let me know please

**Comment by evdama** [comment]
@slightlyfaulty did you have any success implementing reactive movement like this?

**Comment by slightlyfaulty** [comment]
@evdama No I wasn't able to get this working properly. It looks like the codebase has also changed quite a bit since, but it doesn't look like this is supported.

In any case I needed a grid that packed elements in a different way to svelte-grid so I ended up coded my own.

**Comment by evdama** [comment]
@slightlyfaulty There's the `on:change` event, is that something that would help you with your use case? What's your actual use case? Do you want to "trigger" some action once there's movement in the grid caused by a user interaction or is it some other sort of trigger...?

I'm thinking of wirring up svelte-grid with GunDB or Firestore and have grid item positions and content sync accross the internet so to build a distributed real-time kanaban 😎

**Comment by slightlyfaulty** [comment]
@evdama I definitely needed events, but it was in other areas where svelte-grid fell short for my requirements. Reactive movement (while dragging) and elements not being offset to the desired locations when moving other elements were the main issues I had with svelte-grid. My use case was a customizable admin dashboard.

Your distributed kanban idea sounds like fun. But I'm not sure svelte-grid supports multiple grids (?). You could probably code it yourself fairly easily with Svelte though.

**Comment by vaheqelyan** [comment]
https://svelte-grid.now.sh/examples/dynamic I tried to make it possible, tomorrow I will do a little work on it

**Comment by evdama** [comment]
Excellent... I'll be the first... ahem... second one to try it 👏  👏  😆

**Comment by evdama** [comment]
that seems done now i.e. the issue can be closed no?

**Comment by benwoodward** [comment]
This is pretty amazing. It seems to be limited to item movement, however.. it'd be great if items were able to reactively move themselves into available space if an item is resized down. Currently, if you resize an item up, it pushes other items out of the way, but if you resize it back down the items previously pushed out of the way remain in the places they've been 'pushed' to.

**Comment by slightlyfaulty** [comment]
@benwoodward This is one of the main reasons svelte-grid didn't work for my use case. Often you need a grid to "pack" items upward. Svelte-grid seems to use more of a sticky-board layout, so items don't move unless pushed out the way.

Luckily Svelte makes it not-so-super-difficult to code your own interactive grid, if you know how you want it to work.

![grid-demo](https://user-images.githubusercontent.com/2036475/100224890-1b681200-2f26-11eb-9b4f-b240278144ca.gif)

Still working on the resizing, but the bones are there 🙂

**Comment by vaheqelyan** [comment]
@benwoodward i think i understand the problem you are talking about, you can solve this problem. What about functions `gridHelp.normalize`, `gridHelp.findSpace`, `gridHelp.adjust` ? 
v1 had a property called `fillEmpty`

`fillEmpty` - Fills empty spaces with a widget if the widget fits in an empty space.

but it is not supported in the latest version

**Comment by benwoodward** [comment]
@vaheqelyan yes I'm talking about behaviour exactly how @slightlyfaulty's gif illustrates. It's not super important to me right now, but will be in future. Just wanted to get an idea of how difficult it'll be to set up. 

@slightlyfaulty I'd love to see that code, are you gonna open source it?

**Comment by evdama** [comment]
> 1) Often you need a grid to "pack" items upward. 2) Svelte-grid seems to use more of a sticky-board layout, so items don't move unless pushed out the way.

Those two use cases are both very valid and depending on what you need... maybe one or the other, maybe both in the same app so I think rather than giving birth to another package it would be much better to make svelte-grid work for both cases and then simply have a config option to cater to both cases e.g. `<Grid sticky-board={false}>` to have grid items pack upwards and `<Grid sticky-board={true}>` to reflect its current behavior 😎

**Comment by slightlyfaulty** [comment]
@benwoodward It's part of a larger project which will be open sourced when its released. If I do ever package my grid as a standalone library it definitely won't be any time soon...

FWIW I used [React-Grid-Layout](https://strml.github.io/react-grid-layout/examples/0-showcase.html) and [Vue Grid Layout](https://jbaysolutions.github.io/vue-grid-layout/) heavily for reference and inspiration.

@evdama This would be great, but it's far from trivial. I based my grid logic entirely on it packing items upward. If it didn't do this, or did this optionally, my algorithms would look very different and likely much more complex.

**Comment by benwoodward** [comment]
I just added `gridHelp.normalize` into my logic, and it seems to improve the behaviour a little—a single item will move _up_ if you resize another card _over it_. But any other items just remain in place:

```javascript
  let gridItems;
  $: if ($cardData.data) {
    updateGridItems();
  }

  function updateGridItems() {
    let items = gridHelp.adjust(generateLayout($cardData.data.cards), 16);
    items = gridHelp.normalize(items, 16);
    gridItems = items;
  }

  function handleGridItemResize() {
    updateGridItems();
  }
```
```html
      <Grid
        cols={[[1200, 16]]}
        bind:items={gridItems}
        rowHeight={100}
        let:item
        let:dataItem
        dynamic
        on:resize={handleGridItemResize}
        >
```

![svelte-grid-normalize](https://user-images.githubusercontent.com/1472981/100273685-0a6cde80-2fc2-11eb-99ca-727e00f73c23.gif)

**Comment by vaheqelyan** [comment]
@benwoodward try this
```svelte
<Grid on:pointerup={fn} />
<script>
const fn = () => {
 items = gridHelp.normalize(items, COLS); // or items = gridHelp.adjust(items, COLS);
}
</script>
```

**Comment by vaheqelyan** [comment]
okay, I tried it, but it doesn't work,  i will implement it, it is not difficult

**Comment by vaheqelyan** [comment]
![ezgif-7-db1664cca1c6](https://user-images.githubusercontent.com/14107127/101194979-31897700-3678-11eb-99ca-b6e2dd1c2c0c.gif)
`v3.5.0` https://svelte-grid.now.sh/examples/fill-space

**Comment by evdama** [comment]
omg... got no words so there's this instead
![excited_face](https://user-images.githubusercontent.com/39374084/101199714-94254780-3665-11eb-857f-d2fc33bffba1.jpeg)

**Comment by benwoodward** [comment]
Fantastic work @vaheqelyan! Thank you.
