### ISSUE TITLE
Is it possible don't sort blocks after move

### ISSUE THREAD

**Issue by max-frai** [vaheqelyan/svelte-grid#4]
Hello, im building site structure with this grid tool and admin panel.
Everything works okay except sorting which is called each time we translate block, for example, from the center of the grid. Now everything is restructuring and moving. Is it possible now to ignore this and leave just a hole?
You can find such logic here: https://dsmorse.github.io/gridster.js/
<img width="943" alt="изображение" src="https://user-images.githubusercontent.com/24208746/63655332-780ed700-c78f-11e9-8ffa-17f0c4a282cc.png">

**Comment by vaheqelyan** [comment]
Hello, sorry for being late.
You mean free movement ? 
![](https://res.cloudinary.com/dmtrk3yns/image/upload/q_auto/v1566895113/ezgif-2-306c8eb3d6ad_x2mhf6.gif)

Set the property `fillEmpty` to `false` to achieve this effect.

```svelte
<Grid ... fillEmpty={false} />
```
I think it will help you

**Comment by max-frai** [comment]
That's it! I missed this in docs or misunderstood the description :) Thank you ;)
