### ISSUE TITLE
What is the reason that `getContainerHeight` return at least twice as yPerPx?

### ISSUE THREAD

**Issue by ziyuang** [vaheqelyan/svelte-grid#40]
Why is [container.js](https://github.com/vaheqelyan/svelte-grid/blob/master/src/utils/container.js) implemented as `Math.max(getRowsCount(items), 2) * yPerPx` rather than `Math.max(getRowsCount(items), 1) * yPerPx`? Why is the 1-row case special so that the container's height is not the row height?

**Comment by vaheqelyan** [comment]
hmm good catch, I'll check, but I think you're right, even `Math.max` may not be needed here..
