### ISSUE TITLE
Svelte-grid v2 ?

### ISSUE THREAD

**Issue by vaheqelyan** [vaheqelyan/svelte-grid#43]
Major version 2 means much cleaner source code

### Changes

Feature
- Autoscroll
- Faster for touch screens (Probably micro optimization)
- Any user interaction will be disabled while resizing or dragging
- Breakpoints for items.

Breaking change
- `useTransform` will be removed, blocks will be moved using `translate` only
- ~

Fixes (Issues you probably won't see in the 'Issues' section)
- If the minimum width is not set to 1, then your widget will simply disappear.
- If you set breakpoints for your grid.... it will not match the provided coordinates

Refactoring
A new component will be created that will be responsible for moving and resizing the element
Dragging and resizing will be organized using [Pointer events](https://developer.mozilla.org/en-US/docs/Web/API/Pointer_events)
So we'll get rid of these ugly lines

```svelte
<div on:mousedown={item.draggable ? dragOnMouseDown.bind(this, item.id) : null}
        on:touchstart={item.draggable ? dragOnMouseDown.bind(this, item.id) : null}>
{...}
</div>
```

instead we will have this

```svelte
<div on:pointerdown={pointerdown} 
```

With that accomplished, I'll start working on refactoring the `./utils/matrix.js` and `./utils/item.js` files. There is nothing wrong with these files and their implementation

**v2 is more about refactoring and code clean up**

**Comment by frantic0** [comment]
Hi @vaheqelyan, good to know there is a major version coming. 

I would like to take the opportunity to suggest a few things.

1. rename the grid item property "static" to "stationary" or "fixed" or something that does not collide 

export let static; // Error: ParseError: The keyword 'static' is reserved 

2. unit tests framework

I have been thinking about writing unit test for this component but I thought it might be better to work with you on this. have you thought about this before? do you have a favourite one? we could choose between:

mocha (used in svelte and sapper)
jasmine (https://dev.to/d_ir/setting-up-a-svelte-test-environment-2f3e)
jest
enzyme

3. typescript (ts)

svelte has now support for ts, any plans on migrating the s-g code base to it? 

thanks,
FØ

**Comment by vaheqelyan** [comment]
thanks @frantic0 
> 1. rename the grid item property "static" to "stationary" or "fixed" or something that does not collide with a reserved keyword

ok

> 2. unit tests framework

personally I don't like to write tests for front end, and maybe I'm wrong. we can cover every function in `./utils/*.js`, it would be really great.
 If you could help me with that... it would be amazing, if not, nothing bad happened.

> 3. typescript (ts)

nope ::) thanks

using typescript and writing tests would be really helpful if the component were popular. but at this stage it is not really necessary.

**Comment by vaheqelyan** [comment]
'Autoscroll' will be landed a little later
