### ISSUE TITLE
getItem / getItems in order to store the position of the elements

### ISSUE THREAD

**Issue by dexter0323** [vaheqelyan/svelte-grid#44]
Be able to get item or items to store items position so when users refresh the app or load the page again render everything as they left it before.

**Comment by vaheqelyan** [comment]
Hi, you're probably looking for this, https://svelte-grid.now.sh/examples/local-storage

**Comment by evdama** [comment]
I was just adding the restore feature to my grid as well, which works great for non-responsive i.e. without breakpoints.

What doesn't work is when you have a responsive grid and then you want to add the abbility to store it to localStorage `on:change` and restore it on reloading the browser window...

The example below, which is responsive, doesn't work with added store/restore to/from localStorage. Any idea how to add the restore feature to responsive grids? 🤓

```html
<script>
import Grid from "svelte-grid";
import gridHelp from "svelte-grid/build/helper";

const id = () => "_" + Math.random().toString(36).substr(2, 9);

let items = [
  gridHelp.item({
    id: id(),
    breakpoints: {
      3: { x: 0, w: 2, h: 2, y: 0 },
      1: { x: 0, y: 0, w: 1, h: 2 },
    },
  }),

  gridHelp.item({
    id: id(),
    breakpoints: {
      3: { x: 2, w: 1, h: 2, y: 0 },
      1: { x: 0, y: 2, w: 1, h: 2 },
    },
  })
]

const breakpoints = [
  [1024, 3],
  [500, 1],
]


if (typeof window !== "undefined") {
  if (!localStorage.getItem("layout")) {
    localStorage.setItem("layout", JSON.stringify(items));
  } else {
    items = JSON.parse(localStorage.getItem("layout"));
  }
}

const onChange = () => {
  localStorage.setItem("layout", JSON.stringify(items));
};
</script>

<Grid bind:items={items} gap={10} rowHeight={100} let:item {breakpoints} let:index on:change={onChange}>
  <div class=content>
    <h3>{index}</h3>
  </div>
</Grid>

<style>
.content { 
	display: flex;
	justify-content:center;
	align-items: center;
	height: 100%;
}
</style>
```

**Comment by vaheqelyan** [comment]
Yes this is a problem
I think this question is not related to yours @evdama, but anyway.

Here is workaround
https://github.com/vaheqelyan/svelte-grid/commit/d6cd733c5edc4098fde1f7a4cb4695582223d71e, v2.2.0 now you can get the number of columns when you changed the grid.

here is a small example https://svelte-grid.now.sh/examples/responsive-local-storage
By pressing the reset button, the layout can be restored, specifically for the current breakpoint, not for all
This example is not idiomatic, but it may well work.

In general, `svelte-grid` reads elements not from `breakpoints`.

The solution is to store the position and other properties in the `breakpoint` property so the component can automatically decide which position to take

This structure needs to be replaced ( I plan to do it someday )

```
{
  x: 0,
  y: 0,
   ...,
  breakpoints: { ... }
}
```
to this

```
breakpoints: {
  3: {...}
  4: {...}
}
```
regardless of whether you are using a responsive layout or not

**Comment by evdama** [comment]
I'm about to try that now... the example page seems broken somehow though?! Clicking the 'Reset' button also doesn't have any effect 🤔

![Screen Shot 2020-11-08 at 15 58 23](https://user-images.githubusercontent.com/39374084/98468559-50acfa00-21db-11eb-9e23-a3b93309a6fc.png)

**Comment by vaheqelyan** [comment]
Try to clear the cache

**Comment by vaheqelyan** [comment]
let me know if it still doesn't work

**Comment by evdama** [comment]
> let me know if it still doesn't work

Absolutely... https://svelte-grid.now.sh/examples/responsive-local-storage works now... it was also some odd issue with having a bigger width 1600 than the max breakpoint in this example i.e. clearing the cache and then shrinking and growing the window again made it work.

I'll integrate this code into my app example and let you know no later than tomorrow evening 👍

**Comment by BogdanDarius** [comment]
@vaheqelyan There is a bug when you move widget 1 over widget 0 and then refresh they will be overlapped.

**Comment by evdama** [comment]
> @vaheqelyan There is a bug when you move widget 1 over widget 0 and then refresh they will be overlapped.

Yes, I have it working so far and it's great but I see that bug as well... here's some screenshots to show it:

![Uploading Screen Shot 2020-11-08 at 18.59.12.png…](the inital layout to start with...)

**Comment by vaheqelyan** [comment]
I forgot that one widget can also cause other widgets to change their position.
https://svelte-grid.now.sh/examples/responsive-local-storage It's not very well thought out.

```js
const onChange = (ev) => {
 if (ev.detail.cols) {
  if (value.id === ev.detail.id) {
   items = items.map((value) => {
    return {
     ...value,
     breakpoints: {
      ...value.breakpoints,
      [ev.detail.cols]: { x, y, w, h },
     },
    };
   });
  }
 }

 localStorage.setItem("layout-responsive", JSON.stringify(items));
};
```

Try this, you've only updated the current active item before.

**Comment by BogdanDarius** [comment]
> I forgot that one widget can also cause other widgets to change their position.
> https://svelte-grid.now.sh/examples/responsive-local-storage It's not very well thought out.
> 
> ```js
> const onChange = (ev) => {
>  if (ev.detail.cols) {
>   if (value.id === ev.detail.id) {
>    items = items.map((value) => {
>     return {
>      ...value,
>      breakpoints: {
>       ...value.breakpoints,
>       [ev.detail.cols]: { x, y, w, h },
>      },
>     };
>    });
>   }
>  }
> 
>  localStorage.setItem("layout-responsive", JSON.stringify(items));
> };
> ```
> 
> Try this, you've only updated the current active item before.

I've come up with a similar solution, and it works fine. But is this line really needed:
```js
if (value.id === ev.detail.id)
```

Basically I just rearrange all items with their current position.

**Comment by vaheqelyan** [comment]
@BogdanDarius nope, you don't need it. I updated my answer. Thanks!

**Comment by vaheqelyan** [comment]
If it works, it would also be efficient to perform this function when your pointer event is no longer active

**Comment by BogdanDarius** [comment]
> If it works, it would also be efficient to perform this function when your pointer event is no longer active

Yes. The problem is that only 3 events are passed: 
**on:resize, on:change, on:mount**

**Comment by vaheqelyan** [comment]
v2.3.0 now added event **on:pointerup**

**Comment by vaheqelyan** [comment]
@evdama Any questions?

**Comment by evdama** [comment]
> @evdama Any questions?

No, so far so good... all working i.e. restoring a responsive grid now works, that's what I was looking for in svelte-grid as the final cherry on top so to speak 🤣 

I'd like to thank you for the time and effort you put into svelte-grid... I love it and will apply it to more pages in my Sapper app going forward 😎
