### ISSUE TITLE
Resize grid item programmatically (with a function)

### ISSUE THREAD

**Issue by admolofto** [vaheqelyan/svelte-grid#45]
Is there a way to adjust the size of a grid item programmatically (i.e. with a function on button click) that will also adjust surrounding grid items to compensate for the new size?

With my current method, the grid item overlaps adjacent items.

Please see included REPL for example.
https://svelte.dev/repl/cbf42de2ed464534ab5af5d8031d4ae2?version=3.29.0

**Comment by admolofto** [comment]
I have tried using Normalize and Adjust, but they will compact all boxes to the top of the screen to available positions.

**Comment by admolofto** [comment]
That actually might work good enough. Closing the issue.

**Comment by vaheqelyan** [comment]
sorry for being late @admolofto.

Line 14, `items = girdHelp.adjust(items, cols)` must be rewritten to `items = gridHelp.adjust(items, 10)`. my fault
feel free to reopen
