### ISSUE TITLE
repl & source for examples/events

### ISSUE THREAD

**Issue by evdama** [vaheqelyan/svelte-grid#46]
Hi, looking at all the examples at https://svelte-grid.now.sh/examples I was wondering why there's no source or repl for https://svelte-grid.now.sh/examples/events ?

What do you mean by events? Page just says _This particular example has dragging and resizing turned off._

I plan on coupling svelte-grid via GunDB or firebase firestore and build a distributed kanban where people can collaborate and which updates in real-time via p2p... starting from the localstorage example, not writing stuff to local storage though but rather directly into firestore or GunDB 🤓

However, last things, that's why this issue... I'd like to grok what you mean by 'events' on context of svelte-grid?

Other than that, this is amazing work, I love it! 😍

**Comment by vaheqelyan** [comment]
I forgot

**Comment by vaheqelyan** [comment]
forgot to build a website, try again, it will be available
