### ISSUE TITLE
Set grid container height limit/rows

### ISSUE THREAD

**Issue by BogdanDarius** [vaheqelyan/svelte-grid#51]
I would like to suggest a feature: adding a containerHeightLimit or specify a maximum number of rows so the grid can have a limited height when moving widgets.
I'm happy to work on PR. Would like to get your thoughts on this.

**Comment by vaheqelyan** [comment]
why not ?
but i think the name `containerHeightLimit` must be  e.g. `maxRows`. 
the container height is calculated from the farthest grid element + its height.

I think this feature may also be related to "automatic scrolling" (which doesn't exist correctly, this is probably the most missing feature)

**Comment by ka1to1** [comment]
any update on this?

**Comment by vaheqelyan** [comment]
Not yet. sorry @ka1to1

**Comment by Splinteer** [comment]
Just created a PR for this:
https://github.com/vaheqelyan/svelte-grid/pull/145
