### ISSUE TITLE
gap-x / gap-y

### ISSUE THREAD

**Issue by evdama** [vaheqelyan/svelte-grid#52]
- svelte-grid currently has `gap` which sets the gap in x and y directions.
- It would be great to have the ability to distinctively set x and y directions using e.g. `gap-x` and `gap-y`... similar to what Tailwind does https://tailwindcss.com/docs/gap
- Use case: I'd like to optimize for small screens e.g. mobile phones. There I'd like to have less gap horizontally than vertically so I'd set

```
<Grid let:item let:index { breakpoints } gap-x={ 5 } gap-y={ 10 }>
```

Currently I can only choose to have the same gap in both directions which makes the layout look bad in cases of overlapping absolutely positioned badges on the grid items for example...

here with `gap={5}`
![Screen Shot 2020-11-18 at 13 55 14](https://user-images.githubusercontent.com/39374084/99533197-c9634180-29a5-11eb-9103-ea53c5e1786e.png)

and here with `gap={10}`, which looks better vertically but then wastes valuable screen realestate horizontally
![Screen Shot 2020-11-18 at 13 53 04](https://user-images.githubusercontent.com/39374084/99533304-f283d200-29a5-11eb-88f4-e982f0e1f519.png)

**Comment by vaheqelyan** [comment]
I absolutely agree, hope I can publish a new major version this week. I would like to include `gap-x` / `gap-y` (or `gap={[x, y]}`) in the release.

**Comment by vaheqelyan** [comment]
updated example https://svelte-grid.now.sh/examples/gap

**Comment by evdama** [comment]
I have set my gap like this
```html
<Grid let:item let:dataItem let:index cols={ breakpoints } gap={[5, 15]} rowHeight={ 150 } dynamic={ true } bind:items={ gridItems } on:pointerup={ onGridChange } on:mount={ setGridColumns } on:resize={ setGridColumns }>

... svelte markup...
</Grid>
```

What I noticed is that although I set a different gap for x and y, only x is taken into account and both directions have the gap I set for the x axis... this might actually be a bug although maybe an edge case because it works in the [ repl ](https://svelte.dev/repl/7a51dcc6fa574b1dbe6130cda428c039?version=3.29.7) but not in my code with `gap={[5, 15]}` as shown above, here the gap is 5px in x and y directions and not 5px in x direction and 15px in y direction 🤔

**Comment by vaheqelyan** [comment]
it is a bug

**Comment by vaheqelyan** [comment]
https://github.com/vaheqelyan/svelte-grid/blob/master/src/index.svelte#L19 just need `gapY` instead of `gapX`

**Comment by vaheqelyan** [comment]
updated example https://svelte-grid.now.sh/examples/gap, v3.0.1

**Comment by evdama** [comment]
Excellent, already installed v3.0.1 and the result is splendit 

![Screen Shot 2020-11-24 at 19 39 23](https://user-images.githubusercontent.com/39374084/100137577-f5426380-2e8c-11eb-944a-162c102acefc.png)

Thanks again for your time & effort for this amazing package!

**Comment by vaheqelyan** [comment]
thank you too
