### ISSUE TITLE
Error in Breakpoints

### ISSUE THREAD

**Issue by michaelcuneo** [vaheqelyan/svelte-grid#53]
I have made a component which uses the grid layout, but I get an error creating the breakpoints for responsiveness.

```
item.js:10 Uncaught TypeError: Cannot read property '10' of undefined
    at item.js:10
    at Array.map (<anonymous>)
    at responsiveItems (item.js:9)
    at ResizeObserver.<anonymous> (index.svelte:107)
```

```
<script context="module">
	import { API, graphqlOperation } from 'aws-amplify';
	import { listPosts } from '../graphql/queries';

	import PostLink from './PostLink.svelte';
	import Grid from "svelte-grid";
	import gridHelp from "svelte-grid/build/helper/index.mjs";
	import map from 'lodash.map';

	let items;
	let breakpoints = [[1100, 5], [800, 4], [530, 1]];
	let cols = 10;

	export async function preload(page, session) {
		let { posts } = session;

		if (undefined === posts) {
			const res = await API.graphql(graphqlOperation(listPosts));
			posts = res.data.listPosts.items;
			session.posts = posts;
		}

		// Just generate messy layout
		let layout = generateLayout(posts);
		// Helper function which normalize. you need to pass items and columns
		items = gridHelp.normalize(layout, cols);

		return items;
	}

	function generateLayout(posts) {
		return map(new Array(Object.keys(posts).length), function(item, i) {
			return gridHelp.item({
				x: 0,
				y: 0,
				w: 2,
				h: 6,
				resizable: false,
				draggable: false,
				id: posts[i].id,
				post: posts[i],
			});
		});
	}
</script>

<Grid {breakpoints} items={items} {cols} let:item={item} rowHeight={100} gap={10} dynamic>
	<PostLink post={item.post} />
</Grid>
```

**Comment by vaheqelyan** [comment]
you also need to specify breakpoints in your item. `gridHelp.item({})`
Like this 
```
gridHelp.item({
  x: 0,
  y: 0,
  w: 2,
  h: 6,
  resizable: false,
  draggable: false,
  id: posts[i].id,
  post: posts[i],
  breakpoints: {
    5: { x: N, y: N, w: N, h: N },
  },
});
```

**Comment by michaelcuneo** [comment]
Oh! Interesting. How does this calculate for all the X and Y's and such when you want it to be dynamic? A tonne of math, or will it automatically do some things?

**Comment by vaheqelyan** [comment]
drag / resize / move / these functions are very easy to write. the grid works on a 2-dimensional array, Complexity comes when you put all the features together.

**Comment by vaheqelyan** [comment]
Closing it, feel free to reopen

**Comment by michaelcuneo** [comment]
Is there a way to make the grid responsive and resize automatically without having to somehow store all of this data to lay out each slide?

**Comment by vaheqelyan** [comment]
no, you can't, you must provide them to `<Grid/>`.

**Comment by michaelcuneo** [comment]
So if the data is arbitrary, I would need to include the grid items initially and store them into the database on load? But then what if it swaps out and the order is different? It's a bit unusual to say the least.

**Comment by vaheqelyan** [comment]
> But then what if it swaps out and the order is different? It's a bit unusual to say the least.

I don't understand unfortunately
when you change the position of your widgets on the grid, it doesn't change order, but simply assigns positions to everyone who needs to find their new place in the grid

if you want to save the changes that the user made.(drag, resize)..... for this of course you need to save it somewhere 
Better save it in localStorage.

**Comment by vaheqelyan** [comment]
no need to store your grid items in the database...just save it to local storage and then reassign the data for each item
