### ISSUE TITLE
Svelte-grid v3

### ISSUE THREAD

**Issue by vaheqelyan** [vaheqelyan/svelte-grid#54]
**What new ?**
- The way you provide your items has changed, now you have to specify which column the item belongs to

v2
```js
const items = [
  gridHelp.item({/***/}),
  gridHelp.item({/***/}),
]
```
v3
```js
const { item } = gridHelp;
const items = [
  {
    id: id(),
    5: item({
      x: 0,
      y: 0,
      w: 2,
      h: 2,
    }),
    3: item({ x: 0, w: 2, h: 2, y: 0 }),
    1: item({ x: 0, y: 0, w: 1, h: 2 }),
  },
];
```
- `breakpoints` removed, you need to specify it using `cols`

v2

```svelte
<script>
const breakpoints = [
  [1500, 5],
  [1024, 3],
  [500, 1],
];
</script>
<Grid breakpoints={breakpoints} />
```
v3
```svelte
<script>
const breakpoints = [
  [1500, 5],
  [1024, 3],
  [500, 1],
];
</script>
<Grid cols={breakpoints} />
```

- Easier serialization for adaptive grid (https://github.com/vaheqelyan/svelte-grid/issues/44)
  Example https://github.com/vaheqelyan/svelte-grid/blob/master/www/src/routes/examples/responsive-local-storage.svx

- `will-change: transform` replaced with `will-change: auto`

v2 Result
![will-change-transform](https://user-images.githubusercontent.com/14107127/99836261-439aee00-2b7f-11eb-8e67-5efffe938670.png)

v3 Result
![will-change-auto](https://user-images.githubusercontent.com/14107127/99836314-56152780-2b7f-11eb-8b87-616a14e6609c.png)

- "Custom dragger" By setting the ‘custom’ property to true, you can specify the element to which the drag event will be assigned, example https://svelte-grid.now.sh/examples/custom-dragger (https://github.com/vaheqelyan/svelte-grid/issues/25)

- Gap for x and y axes (https://github.com/vaheqelyan/svelte-grid/issues/52), example https://svelte-grid.now.sh/examples/gap
---
No changelog, sorry (Will work on it later https://github.com/vaheqelyan/svelte-grid/issues/50), hope all repls are up to date, the big upcoming deal will be auto-scrolling, outdated packages updated to the latest version

**Comment by evdama** [comment]
> The way you provide your items has changed, now you have to specify which column the item belongs to

I'm in the middle of migration from v2 to v3.

In v2 I was storing additional data inside the grid object e.g. another sub-object called `content` or the `flippedToBack` property:

```
      gridHelp.item( {
        content: {
          category: 'animals',
          ccc: 'some urls to communication channels',
          requirements: 'Your email-verified account which you get by simply signing up.',
          title: 'Care',
        },
        breakpoints: {
          1: { x: 0, y: 0, w: 1, h: 2 },
          2: { x: 0, y: 0, w: 2, h: 2 },
          3: { x: 0, y: 0, w: 3, h: 2 },
        },
        flippedToBack: false,
        id: nanoid(),
        itemConfig: null,
      } ),
```

Inside the svelte markup I was then reading those properties for each grid item with markup like this
```html
{#if is.string(item.itemConfig) }
  <div class="text-xl font-black tracking-widest text-eight md:text-2xl">{ item.content.title }</div>
{/if}
```
With the above data/item structure that worked well but of course blows up now
![Screen Shot 2020-11-23 at 18 22 20](https://user-images.githubusercontent.com/39374084/99995313-77ae2300-2dba-11eb-8274-a0548b00edac.png)

So far I have migrated the data/item structure to this one below which still gives the console error because it looks I would have to e.g. duplicate the `itemsConfig`, `content` etc. propierties for each col line i.e. three times in this case

```
      {
        content: {
          category: 'animals',
          ccc: 'some urls to communication channels',
          requirements: 'Your email-verified account which you get by simply signing up.',
          title: 'Care',
        },
        1: item({ x: 0, y: 0, w: 1, h: 2 }),
        2: item({ x: 0, y: 0, w: 2, h: 2 }),
        3: item({ x: 0, y: 0, w: 3, h: 2 }),
        flippedToBack: false,
        id: nanoid(),
        itemConfig: null,
      },
```

**Comment by evdama** [comment]
A second thing I noticed is that my reset function stopped working so I changed it accordingly to be that in v3

```
    resetGrid = () => {
      gridItems = gridItems.map( (value, index) => {
        const originalItem = initialGridLayout[ index ][ gridColumns ]
        return {
          ...value,
          [ gridColumns ]: originalItem
        }
      })
    }
```
that said I still have this one around from v2 which works but is probably not entirely correct?
```
    onGridChange = event => {
      if (event.detail.cols) {
        gridItems = gridItems.map( value => {
          return {
            ...value,
            breakpoints: {
              ...value.breakpoints,
              [ event.detail.cols ]: { x, y, w, h },
            },
          }
        })
      }
    }
```

**Comment by vaheqelyan** [comment]
> With the above data/item structure that worked well but of course blows up now with v3 since the structure changed

```svelte
<Grid let:dataItem>
  {dataItem.itemConfig}
  {item?.fixed}
</Grid>
```
![image](https://user-images.githubusercontent.com/14107127/100099097-63306000-2e78-11eb-8aa4-9c4d30063f30.png)

> A second thing I noticed is that my reset function stopped working so I changed it accordingly to be that in v3

we can consider it a workaround for this https://github.com/vaheqelyan/svelte-grid/issues/44#issuecomment-724132490 , but no, you don't need it anymore, I released v3 mainly for this. you can remove this function

**Comment by evdama** [comment]
I see 💡 😆

I have added `<Grid let:dataItem>` and changed my datastructure to
```
      {
        data: {
          content: {
            category: 'animals',
            ccc: 'some urls to communication channels blabla',
            how: 'Both parties involved... blabla'
          },
          flippedToBack: false,
          itemConfig: null,
        },
        1: item({ x: 0, y: 0, w: 1, h: 2 }),
        2: item({ x: 0, y: 0, w: 2, h: 2 }),
        3: item({ x: 0, y: 0, w: 3, h: 2 }),
        id: nanoid(),
      },
```
which let's me access it in the markup like this
```html
{#if dataItem.data.itemConfig != null }
  <div>{ dataItem.data.itemConfig }</div>
{/if}
```

**Comment by evdama** [comment]
Regarding the my `onGridChange` function... I have it in order to restore from `localStorage` using the `on:pointerup` event:

```
<Grid let:item let:index cols={ breakpoints } gap={[5, 15]} rowHeight={ 150 } dynamic={ true } bind:items={ gridItems } on:pointerup={ onGridChange } on:mount={ setGridColumns } on:resize={ setGridColumns } let:dataItem>

... svelte markup...
</Grid>
```
```
    onGridChange = event => {
      if (event.detail.cols) {
        gridItems = gridItems.map( value => {
          return {
            ...value,
          }
        })
      }

      localStorage.setItem(`edm-sg-layout-for-${ $page.host }${ $page.path }`, JSON.stringify(gridItems))
      showGridResetButton = true
    }
```

**Comment by evdama** [comment]
Another thing I noticed is that although I set a different gap for x and y, only x is taken into account and both directions have the gap I set for the x axis... this might actually be a bug although maybe an edge case because it works in the [ repl ](url)https://svelte.dev/repl/7a51dcc6fa574b1dbe6130cda428c039?version=3.29.7 but not in my code with `gap={[5, 15]}` as shown below, here the gap is 5px in x and y directions 🤔

**Comment by vaheqelyan** [comment]
You can still shorten your function.
```js
    onGridChange = event => {
      localStorage.setItem(`edm-sg-layout-for-${ $page.host }${ $page.path }`, JSON.stringify(gridItems))
      showGridResetButton = true
    }
```
Of course, it's your choice whether to save your data with the item in localStorage or just save the cordinates

**Comment by evdama** [comment]
Right, thanks, I'll just need the svelte-grid layout actually because when I'm done testing and designing I'll move the actuall data to something like Firestore or GunDB... ok, so, since I just need the svelte-grid layout coordinates I'd just do what exactly?... given the currently stored gridItems I could filter and only grab everything that's not `data` or `id`?
![Screen Shot 2020-11-24 at 18 54 14](https://user-images.githubusercontent.com/39374084/100133073-9aa60900-2e86-11eb-94f7-930c112d5bf8.png)

**Comment by evdama** [comment]
I've also read the [usage part of the website](https://svelte-grid.now.sh/usage) again but there's one bit that I don't grasp:

- dataItem - Returns your item, you can use it to access your data
- item - Returns the item for the current breakpoint

I know now semantically what I use dataItem for and how the syntax looks so I get the data I need from my svelte store, which has the items array, into my `<Grid>` component, and thus in the markup.

So far so good, but based on some data item like the one below, what would `item` get me, and in particular, what would I use it for? Isn't that just for svelte-grid internally to do its magic? I just want to understand at least every aspect of the user-side of svelte-grid so I don't miss out on anything 🤣

```js
{
        data: {
          content: {
            category: 'animals',
            ccc: 'some urls to communication channels blabla',
            how: 'Both parties involved... blabla'
          },
          flippedToBack: false,
          itemConfig: null,
        },
        1: item({ x: 0, y: 0, w: 1, h: 2 }),  // <--- what do I use the return value of 'item' for for example?
        2: item({ x: 0, y: 0, w: 2, h: 2 }),
        3: item({ x: 0, y: 0, w: 3, h: 2 }),
        id: nanoid(),
      },
```

With this responsive repl example, how would using `item` look like in particular incl a use case?
https://svelte.dev/repl/2cf339cc1dc14223a1457e386195e52d?version=3.29.7

**Comment by vaheqelyan** [comment]
for example, you can access the `fixed` property from `item?.fixed` and assign styles to it
> what would I use it for? Isn't that just for svelte-grid internally to do its magic?

yes, but you have access to them as well.

**Comment by evdama** [comment]
> for example, you can access the `fixed` property from `item?.fixed` and assign styles to it
> 
> > what would I use it for? Isn't that just for svelte-grid internally to do its magic?
> 
> yes, but you have access to them as well.

ah, ok, understood... I've been using `fixed` before to show a badge in my UI that a certain grid tile can't be resized and/or dragged... that kind of use cases I knew, just thought to ask because who knows, there might have been more 😊

**Comment by vaheqelyan** [comment]
> https://github.com/vaheqelyan/svelte-grid/issues/54#issuecomment-733141200

Yes something like that, you can only store breakpoints and id and then reassign data to that id
