### ISSUE TITLE
Static height not set

### ISSUE THREAD

**Issue by BogdanDarius** [vaheqelyan/svelte-grid#55]
In this demo the height is not set during first load if zoom is 110% or below. To fix it you have to zoom in and out again any ideas on this issue?
https://svelte-grid.now.sh/examples/responsive

![img_1](https://user-images.githubusercontent.com/25986436/100027025-96311000-2df4-11eb-9307-4a6ac0567fd5.png)
![img_2](https://user-images.githubusercontent.com/25986436/100027027-96c9a680-2df4-11eb-8878-f19912d3010f.png)

**Comment by vaheqelyan** [comment]
Yes, of course, I'll fix it, ....wrong breakpoint numbers,

**Comment by vaheqelyan** [comment]
fixed, it happens everywhere
