### ISSUE TITLE
Z-index/stacking order of items

### ISSUE THREAD

**Issue by admolofto** [vaheqelyan/svelte-grid#60]
What is the best way to adjust the stacking order/z-index of grid items?

I have a grid item that opens a dropdown from within the item. This dropdown is displayed behind the other grid items depending on which order they are generated from the items array. 

Changing the z-index of the dropdown doesn't fix the issue.

Any advice would be greatly appreciated.

**Comment by evdama** [comment]
Each of my grid tiles has a background image and a button which is *above* the background image i.e. what I've done is give the grid item a position of relative and the button inside a postion of *absolute* with a z-index bigger than the background image and the grid tile... works...

**Comment by vaheqelyan** [comment]
when dragging or resizing element, `z-index` is set to 3. an inactive item has no z-index. can you create a [repl](https://svelte.dev/repl/hello-world?version=3.30.0) so I can better understand the problem.

You can just fork [this one](https://svelte.dev/repl/35a506b9456d463ab441841859e1bb9f?version=3.30.0)

**Comment by admolofto** [comment]
See here: 
https://svelte.dev/repl/1144b22f1cdf4377a3dcee2a1897e0bb?version=3.30.0
I would like the dropdown of the first card to overlap the second card.

Sorry if I wasn't clear.

**Comment by vaheqelyan** [comment]
here is my fork https://svelte.dev/repl/bb14676987504797a690a7f2a4b24982?version=3.30.0.
In your example your element just went out of bounds.

**Comment by admolofto** [comment]
@vaheqelyan  Thanks for looking at this. Yes, the element is suppose to go out of bounds. The dropdown goes beyond the bounds of my grid item. I would like the dropdown to display on top of the other element.

**Comment by vaheqelyan** [comment]
change styles a little bit https://svelte.dev/repl/93f861aff3234eb99c6046663cb73fdf?version=3.30.0

**Comment by vaheqelyan** [comment]
The element is in a lower stacking context due to its parent’s z-index level, in this case `.svlt-grid-item` has no `z-index`.
https://svelte.dev/repl/93f861aff3234eb99c6046663cb73fdf?version=3.30.0

**Comment by admolofto** [comment]
Ah okay I should use the .svlt-grid-item class to set the z-indexs not the children of the grid items. Thanks for your help I know you must be busy and I appreciate all the hard work you put into this!
