### ISSUE TITLE
Bug: It's possible to resize items outside the bounds of the grid

### ISSUE THREAD

**Issue by benwoodward** [vaheqelyan/svelte-grid#63]
If the right edge is on the edge of the grid, and the item is sized below it's maximum width then it's possible to resize the item outside of the grid boundary: 

![image](https://user-images.githubusercontent.com/1472981/101265376-d3a97c00-37aa-11eb-8324-dfc35d831b2d.png)

Experiencing this in `3.5.0`.

**Comment by vaheqelyan** [comment]
should be fixed in `v3.5.1`

**Comment by vaheqelyan** [comment]
feel free to reopen

**Comment by benwoodward** [comment]
Your update solved the problem. 👌🏻
