### ISSUE TITLE
Feature request: prevent grid item from visually resizing past min/max when dragging resizer

### ISSUE THREAD

**Issue by benwoodward** [vaheqelyan/svelte-grid#65]
![svelte-grid-resize-issue](https://user-images.githubusercontent.com/1472981/101739669-bc60ea80-3b2c-11eb-870e-9c2a996061c3.gif)

**Comment by vaheqelyan** [comment]
Yes, absolutely, right now i am concentrating all my knowledge to add a smooth beautiful auto scrolling feature. so i think we can delay this a little bit

**Comment by benwoodward** [comment]
No worries. I'm just documenting issues as I find them. I'll hopefully be able to contribute some fixes for some things when I have more time and familiarity with the code.

**Comment by vaheqelyan** [comment]
wip (code looks cleaner too) I'll publish it soon ![f5f36081-8ced-4435-b4a9-adff722e](https://user-images.githubusercontent.com/14107127/102712488-2458c300-42db-11eb-8b27-ab03a2095df7.gif)

**Comment by vaheqelyan** [comment]
available for version `v3.6.0`
