### ISSUE TITLE
"Uncaught TypeError: undefined is not a function" in <MoveResize cols={getComputedCols}

### ISSUE THREAD

**Issue by frantic0** [vaheqelyan/svelte-grid#66]
Hi @vaheqelyan 

I am trying to update to svelte-grid **v.3.5.1**. I've found your issue https://github.com/vaheqelyan/svelte-grid/issues/54 and am upgrading accordingly (refactoring grid-items, breakpoints to cols, etc). 

However, there is a runtime an error preventing svelte-grid from loading, even without any items. 

```
index.svelte:26 Uncaught (in promise) TypeError: undefined is not a function
    at Object.$$self.$$.update (index.svelte:26)
    at init (index.mjs:1396)
    at new Src (index.svelte:43)
```

where index.svelte:26 is
```
<MoveResize ...  
   cols={getComputedCols}
```

where index.svelte:43 is

```
  import { debounce, getColumn } from "./utils/other.js";
//line 43
  import MoveResize from "./MoveResize/index.svelte";
```

so `getComputedCols` is **_undefined_** on load.

Do you have any suggestion on how I can fix this?

Many thanks

**Comment by vaheqelyan** [comment]
Can I see your full stack trace ? it won't be easy for me to tell what's wrong with the component.
https://github.com/vaheqelyan/svelte-grid/blob/master/src/index.svelte#L105 have you provided breakpoints ?

**Comment by frantic0** [comment]
oh no, I found that it was the old `gap` parameter value that was causing a type error (integer rather than a list)...
