### ISSUE TITLE
Demo code doesn't show anything until window is resized

### ISSUE THREAD

**Issue by natemartinsf** [vaheqelyan/svelte-grid#67]
I'm sure I'm something stupid here, so I apologize in advance.

I'm trying to get the "basic example" to work in my project, but it's just rendering a blank screen until I resize the screen

Steps to reproduce:
1) Create a new Svelte project as described here using degit: https://svelte.dev/blog/the-easiest-way-to-get-started
2) Install svelte-grid
3) Replace App.svelte with the content of the "basic example" and start server
4) Nothing shows up
5) Resize the window, and the demo looks as expected.

**Comment by vaheqelyan** [comment]
similar to https://github.com/vaheqelyan/svelte-grid/issues/55. you just need to create a container.  my fault, the examples do not include this
```svelte
<style>
  .container {
    max-width: 100%;
    max-width: 300px;
    margin: 0 auto;
  }
</style>

<div class="container">
  <Grid bind:items={items} rowHeight={100} let:dataItem {cols}>
    <div class="content">{dataItem.id}</div>
  </Grid>
</div>
```

**Comment by vaheqelyan** [comment]
I'll update them all soon.

**Comment by vaheqelyan** [comment]
feel free to reopen
