### ISSUE TITLE
Resize card size on click

### ISSUE THREAD

**Issue by ranjitindx** [vaheqelyan/svelte-grid#68]
Hi Team,
Facing issue with resizing card size, Each card needs functionality with change card size, On change, size button click change width from 2 to 4.
demo link https://svelte.dev/repl/1396616cd3ca4734b2999b02ef70591f?version=3.31.0

Eg:
Default card width size 2, change card size button click change card width to 4,
unable to resize  
Please help me with it

**Comment by vaheqelyan** [comment]
i clicked on each button and then tried to resize them all, i was able to resize them all. maybe you have something in the console you can share with it?

**Comment by ranjitindx** [comment]
@vaheqelyan figured out for card resize on the button inside button click thank you so much for reply

**Comment by vaheqelyan** [comment]
nice, feel free to reopen
