### ISSUE TITLE
How to serialise and restore?

### ISSUE THREAD

**Issue by analytically** [vaheqelyan/svelte-grid#7]
Would be excellent if there's an example :-)

**Comment by MintyMods** [comment]
**Snap** - was literally just typing out the same comment #8 :)

**Comment by vaheqelyan** [comment]
I'll put in the Examples section tomorrow

**Comment by vaheqelyan** [comment]
Here is https://github.com/vaheqelyan/svelte-grid/blob/master/www/src/routes/examples/localStorage.svelte. I haven't deployed the website yet

**Comment by vaheqelyan** [comment]
[https://svelte-grid.now.sh/examples/localStorage](https://svelte-grid.now.sh/examples/localStorage)
It does not appear in route /examples
