### ISSUE TITLE
could support take note in grid ? 

### ISSUE THREAD

**Issue by steveyang331** [vaheqelyan/svelte-grid#74]
support markdown, take note in grid.

**Comment by vaheqelyan** [comment]
I don't understand the question, could you please give me more details ?

**Comment by steveyang331** [comment]
support markdown ,and allow to take notes in grid or allow upload images in grid. like Pinterest. 

I don't how to let you understand clearly, I think it's really clearly.

**Comment by frantic0** [comment]
@steveyang331 you need to wrap up an editor component or a markdown component in a svelte-grid item.

**Comment by frantic0** [comment]
@steveyang331 have a look at https://github.com/mimic-sussex/sema where you can find how I did that with the codeMirror editor.
