### ISSUE TITLE
<X> was created without expected prop 'scroller'

### ISSUE THREAD

**Issue by frantic0** [vaheqelyan/svelte-grid#79]
Hi @vaheqelyan 

started to get this warning. 

What am I missing? 

Best,
F

**Comment by vaheqelyan** [comment]
oh yes, I did notice the same thing in development mode
The grid expects a `scroller` property to do autoscrolling, by default, it refers to (`document.documentElement`)

**Comment by frantic0** [comment]
I just noticed your auto-scroll example. 

It might be useful to instruct the user to click and drag a grid item to the border of the grid container to see the desired effect.

**Comment by woothu** [comment]
@vaheqelyan Could you assign a default value to the prop to avoid the warning?

**Comment by vaheqelyan** [comment]
I hope to do it on Saturday
