### ISSUE TITLE
Grid not initialised to the available screen size when loaded as SPA using svelte-spa-router

### ISSUE THREAD

**Issue by MintyMods** [vaheqelyan/svelte-grid#8]
Hi Vahe,

Thank you for your excellent code which is perfect to replace the ResizeObservable which I **was** using (which doesn't yet have great browser support). 

I do have a number of queries if you would be so kind:-

Could you clarify how to serialize and de-serialize the grid as this doesn't seem to be covered in the examples and I can't see any reference within the source code. I would guess I just need to JSON serialize the items collections but thought I would ask for the correct approach to be sure.

I also have a strange issue but suspect it is due to either my usage of the grid or my lack of experience with Svelte (I have only been using it for about a month but I do totally love it)

Basically the grid not initializing to the available screen size when loaded using routes. To see the issue in action go to the following [prototype](https://www.mintymods.info/demo.html) and then click on the hamburger and select the 'VIEWS' section. This will change to a page containing the grid and you will notice that the grid doesn't take the available width in the browser. Resizing the browser triggers a re-flow and the space is then used. Loading the page [directly](https://www.mintymods.info/demo.html#/views) or refreshing the page does not have the issue.

I suspect this is an issue with my css styling in my page but if you have any idea as to why it is behaving like this or can suggest any possible fixes that would be appreciated. 

Thank you again for the cool component.

**Comment by vaheqelyan** [comment]
Strange. If you go to https://svelte-grid.now.sh/, it works very well, for example, zoom the page and and switch between pages. I don't think the problem is with your css code. Make sure that the element that wraps the container does not limit the width.

**Comment by vaheqelyan** [comment]
OK I'll dig more. I will try to make a menu and see what causes this problem

**Comment by MintyMods** [comment]
Thank you. Let me know if there is anything I can do to help.

**Comment by vaheqelyan** [comment]
Sure

**Comment by MintyMods** [comment]
@vaheqelyan 

I'm going to close this one as while trying to debug the issue I swapped out [svelte-spa-router](https://www.npmjs.com/package/svelte-spa-router) with a couple of alternatives and only [svelte-spa-router](https://www.npmjs.com/package/svelte-spa-router) shows the issue. 

So I do not think the issue is caused by svelte-grid and I have a work around by migrating to [svelte-routing](https://github.com/EmilTholin/svelte-routing) for my routing.

Thank you again for your help with this.
