### ISSUE TITLE
NaN width and height

### ISSUE THREAD

**Issue by MarcGodard** [vaheqelyan/svelte-grid#83]
I just copied the most basic example without any styling:

```
  const id = () => "_" + Math.random().toString(36).substr(2, 9);

  let items = [
    gridHelp.item({ x: 0, y: 0, w: 2, h: 2, id: id() }),
    gridHelp.item({ x: 2, y: 0, w: 2, h: 2, id: id() }),
  ]
```
and
```
    <Grid cols={3} bind:items={items} let:item={item}>
      <div>{item.id}</div>
    </Grid>
```
This is what shows in the console.

<img width="490" alt="Screen Shot 2021-03-07 at 3 07 30 PM" src="https://user-images.githubusercontent.com/5016637/110253184-e6bd1b00-7f56-11eb-9d3a-3aa3a21c787b.png">

Can't figure out what i am missing.

**Comment by vaheqelyan** [comment]
Take a look at this example https://github.com/vaheqelyan/svelte-grid/blob/master/www/src/routes/examples/basic.svx
`cols` -> it is a 2d array. `[ [1000, 6], [800, 3] ]`, breakpoint size, column size.

suppose that if your container is `1000px` wide, your columns change by six, etc.
so it changes to `6`, then it will search for your item and find the key `6`.
```js
item({
  [6]: { w: N, h: N, x: N, y: N },
  [3]: { w: N, h: N, x: N, y: N },
})
```

**Comment by MarcGodard** [comment]
@vaheqelyan Thanks for your help. However, I changed the existing cols attribute with the 2d array, and same results.

```
  const id = () => "_" + Math.random().toString(36).substr(2, 9);

  const cols = [
    [ 1100, 6 ],
  ]

  let items = [
    {
      6: gridHelp.item({
        x: 0,
        y: 0,
        w: 2,
        h: 2,
      }),
      id: id(),
    },

    {
      6: gridHelp.item({
        x: 2,
        y: 0,
        w: 2,
        h: 2,
      }),
      id: id(),
    },
  ];
  ```
  and 
  ```
    <Grid bind:items={items} let:item={item} {cols}>
      <div>{item.id}</div>
    </Grid>
  ```

**Comment by vaheqelyan** [comment]
You missed creating a container. `1100 `is the width of your container.
```svelte
<style>
.container {
  max-width: 1100px:
  width: 100%;
}
</style>

<div class=container>
  <Grid />
</div>
```

**Comment by MarcGodard** [comment]
Now is working for width but not height. lol

I am guessing I need to do the same for height?

<img width="609" alt="Screen Shot 2021-03-09 at 6 12 26 PM" src="https://user-images.githubusercontent.com/5016637/110551152-03965180-8103-11eb-9541-a72409dd9cd7.png">

Will play more with this.

**Comment by vaheqelyan** [comment]
Please specify `rowHeight`

**Comment by vaheqelyan** [comment]
Feel free to reopen

**Comment by MarcGodard** [comment]
Sorry, but I built my own it its good. Thanks for your help.
