### ISSUE TITLE
Performance improvement for future using CSS Grids

### ISSUE THREAD

**Issue by Immortalin** [vaheqelyan/svelte-grid#86]
The grid resizing and computation can be offloaded to the browser with the new CSS grid specifications. It also supports nesting via subgrids.

**Comment by Immortalin** [comment]
I just noticed [this](https://github.com/vaheqelyan/svelte-grid/issues/71#issuecomment-763859038), @vaheqelyan I am curious as to why CSS grid isn't used the grid logic.

**Comment by vaheqelyan** [comment]
At first i have tried using css grid(i do not remember but something went wrong and i could not accomplish that using css grid).
Then I decided to write a grid model from scratch..

I think the performance is ok

**Comment by vaheqelyan** [comment]
ok, I think this can be closed
