### ISSUE TITLE
Issue when trying to Remove Grids

### ISSUE THREAD

**Issue by AdithyaR-afk** [vaheqelyan/svelte-grid#88]
Issue seen directly on the svelte [repl](https://svelte.dev/repl/6f3685b564d74eb0812cfe10e41f3186?version=3.35.0) and in the attached [source](https://github.com/vaheqelyan/svelte-grid/tree/master/www/src/routes/examples/add_remove.svx)

Please refer to the gif attached. After creating a random sized grid, when trying to close , clicking the close button causes it to select the grid itself. So i have to deselect the grid and only then i am to close it. Also one more issue is neither dragging or closing the button does anything  and one has to deselect the grid for it to work properly
![issue](https://user-images.githubusercontent.com/26501256/112336242-eb1d5e00-8ce2-11eb-977f-5cd9fcfd4162.gif)

**Comment by vaheqelyan** [comment]
Oh yes, I fixed it on www [https://svelte-grid.now.sh/examples/add_remove](https://svelte-grid.now.sh/examples/add_remove)

I think adding the `user-select: none` property will fix this problem. I've updated the repl

**Comment by AdithyaR-afk** [comment]
Thanks...that did the trick
