### ISSUE TITLE
Vite/Snowpack ESM Bundler do not work

### ISSUE THREAD

**Issue by SlinSo** [vaheqelyan/svelte-grid#94]
Currently it is not possbile to use svelte-grid with ESM Bundlers like Vite, because of the lodash throttle dependency.
Please pull #87 as this is not only svelte-kit related. I am not using svelte-kit but Vite for my SPA projects.

**Comment by vaheqelyan** [comment]
I'll do it this weekend.

**Comment by vaheqelyan** [comment]
`v5.0.0` - update to the latest version, should fix the issue
