### ISSUE TITLE
image and text?

### ISSUE THREAD

**Issue by j2l** [vaheqelyan/svelte-grid#99]
Hello,
Great package, thanks!

I'd like different HTML content in each cell.
I play with it for a few hours and searched the issues for images and didn't find one, so I guess my code is not optimal :smile: 
```
<div class="demo-container size">
	  <Grid bind:items={items} rowHeight={100} let:item let:dataItem {cols} let:index on:change={onChange} >
		<div class=demo-widget>
			<img id="inside" src={dataItem.img} alt={dataItem.img}>
			{index}
		</div>
	  </Grid>
	</div>
...
let layoutOriginal = [
	  {
		6: gridHelp.item({
		  x: 0,
		  y: 0,
		  w: 2,
		  h: 2,
		}),
		img: "space.png",
	  },
```
I can't really move a cell, it autoscrolls and goes to lalaland.
But hey, when I can finally master a cell move I get a temporary limited overlay bonus (only 1 on 0, removed as soon as I move 0):
![image](https://user-images.githubusercontent.com/65325/126874706-563da987-e2bc-4d18-a284-1a66eca3426e.png)
It's fun but not what I want :)

How to add more than one line of text?
I tried
```
{#if dataItem.id == 0}
			<img id="inside" src={dataItem.img} alt={dataItem.img}>
			{/if}
```
but it's not working, it removes the image of cell 0.

So, how to add different HTML tags and content for each cell?

**Comment by vaheqelyan** [comment]
https://svelte.dev/repl/3986952efde64489b6651475787cec5e?version=3.40.2

If you don't need predefined components... you can use the text and associate that text with the component

```svelte
<div class=demo-container>
  <Grid bind:items={items} rowHeight={100} let:item let:dataItem {cols}>
    <div class=demo-widget>
      <svelte:component this={dataItem.component} />
    </div>
  </Grid>
</div>


<script>
const COMPONENTS = {
  text: Text,
  image: Image
}

let data = {
  // ...
  id: uid(),
  component: 'text' | 'image' // Or something else, depending on your needs
}
</script>
```

**Comment by j2l** [comment]
Fantastic! Thank you @vaheqelyan 
It works great for me.
